from states import State

STATE_DETAILS = {
  State.AK: {'hc-key': 'us-ak', 'senate': 2, 'house': 1},
  State.AL: {'hc-key': 'us-al', 'senate': 2, 'house': 7},
  State.AR: {'hc-key': 'us-ar', 'senate': 2, 'house': 4},
  State.AZ: {'hc-key': 'us-az', 'senate': 2, 'house': 9},
  State.CA: {'hc-key': 'us-ca', 'senate': 2, 'house': 53},
  State.CO: {'hc-key': 'us-co', 'senate': 2, 'house': 7},
  State.CT: {'hc-key': 'us-ct', 'senate': 2, 'house': 5},
  State.DC: {'hc-key': 'us-dc', 'senate': 0, 'house': 3},
  State.DE: {'hc-key': 'us-de', 'senate': 2, 'house': 1},
  State.FL: {'hc-key': 'us-fl', 'senate': 2, 'house': 27},
  State.GA: {'hc-key': 'us-ga', 'senate': 2, 'house': 14},
  State.HI: {'hc-key': 'us-hi', 'senate': 2, 'house': 2},
  State.IA: {'hc-key': 'us-ia', 'senate': 2, 'house': 4},
  State.ID: {'hc-key': 'us-id', 'senate': 2, 'house': 2},
  State.IL: {'hc-key': 'us-il', 'senate': 2, 'house': 18},
  State.IN: {'hc-key': 'us-in', 'senate': 2, 'house': 9},
  State.KS: {'hc-key': 'us-ks', 'senate': 2, 'house': 4},
  State.KY: {'hc-key': 'us-ky', 'senate': 2, 'house': 6},
  State.LA: {'hc-key': 'us-la', 'senate': 2, 'house': 6},
  State.MA: {'hc-key': 'us-ma', 'senate': 2, 'house': 9},
  State.MD: {'hc-key': 'us-md', 'senate': 2, 'house': 8},
  State.ME: {'hc-key': 'us-me', 'senate': 2, 'house': 2},
  State.MI: {'hc-key': 'us-mi', 'senate': 2, 'house': 14},
  State.MN: {'hc-key': 'us-mn', 'senate': 2, 'house': 8},
  State.MO: {'hc-key': 'us-mo', 'senate': 2, 'house': 8},
  State.MS: {'hc-key': 'us-ms', 'senate': 2, 'house': 4},
  State.MT: {'hc-key': 'us-mt', 'senate': 2, 'house': 1},
  State.NC: {'hc-key': 'us-nc', 'senate': 2, 'house': 13},
  State.ND: {'hc-key': 'us-nd', 'senate': 2, 'house': 1},
  State.NE: {'hc-key': 'us-ne', 'senate': 2, 'house': 3},
  State.NH: {'hc-key': 'us-nh', 'senate': 2, 'house': 2},
  State.NJ: {'hc-key': 'us-nj', 'senate': 2, 'house': 12},
  State.NM: {'hc-key': 'us-nm', 'senate': 2, 'house': 3},
  State.NV: {'hc-key': 'us-nv', 'senate': 2, 'house': 4},
  State.NY: {'hc-key': 'us-ny', 'senate': 2, 'house': 27},
  State.OH: {'hc-key': 'us-oh', 'senate': 2, 'house': 16},
  State.OK: {'hc-key': 'us-ok', 'senate': 2, 'house': 5},
  State.OR: {'hc-key': 'us-or', 'senate': 2, 'house': 5},
  State.PA: {'hc-key': 'us-pa', 'senate': 2, 'house': 18},
  State.PR: {'hc-key': 'us-pr', 'senate': 0, 'house': 0},
  State.RI: {'hc-key': 'us-ri', 'senate': 2, 'house': 2},
  State.SC: {'hc-key': 'us-sc', 'senate': 2, 'house': 7},
  State.SD: {'hc-key': 'us-sd', 'senate': 2, 'house': 1},
  State.TN: {'hc-key': 'us-tn', 'senate': 2, 'house': 9},
  State.TX: {'hc-key': 'us-tx', 'senate': 2, 'house': 36},
  State.UT: {'hc-key': 'us-ut', 'senate': 2, 'house': 4},
  State.VA: {'hc-key': 'us-va', 'senate': 2, 'house': 11},
  State.VT: {'hc-key': 'us-vt', 'senate': 2, 'house': 1},
  State.WA: {'hc-key': 'us-wa', 'senate': 2, 'house': 10},
  State.WI: {'hc-key': 'us-wi', 'senate': 2, 'house': 8},
  State.WV: {'hc-key': 'us-wv', 'senate': 2, 'house': 3},
  State.WY: {'hc-key': 'us-wy', 'senate': 2, 'house': 1}
}

hc_keys_by_state = {k: v['hc-key'] for k, v in STATE_DETAILS.iteritems()}
electoral_college_votes_by_state = {k: v['senate'] + v['house'] for k, v in STATE_DETAILS.iteritems()}

